const vendors = [
  {
    id: 1,
    name: "Elegance Cafeteria",
    address: "123 Main St, Downtown",
    rating: 4.5,
    time: "30min",
    category: "Café",
    status: "Open",
    image: "https://example.com/images/elegance-cafe.jpg",
  },
  {
    id: 2,
    name: "Sunrise Bakery",
    time: "30min",
    address: "456 Oak Ave, Uptown",
    rating: 4.7,
    status: "Open",
    category: "Bakery",
    image: "https://example.com/images/sunrise-bakery.jpg",
  },
  {
    id: 3,
    name: "Green Garden Restaurant",
    address: "789 Pine Rd, Midtown",
    rating: 4.3,
    status: "Open",
    time: "30min",
    category: "Restaurant",
    image: "https://example.com/images/green-garden.jpg",
  },
  {
    id: 4,
    name: "Coffee Corner",
    address: "321 Elm St, Downtown",
    rating: 4.6,
    feature: true,
    status: "Open",
    time: "30min",
    category: "Café",
    image: "https://example.com/images/coffee-corner.jpg",
  },
  {
    id: 5,
    time: "30min",
    name: "Bistro Delight",
    address: "654 Maple Ave, Uptown",
    rating: 4.4,
    feature: true,
    status: "Open",
    category: "Restaurant",
    image: "https://example.com/images/bistro-delight.jpg",
  },
];

export default vendors;
